language: python
python:
  - "2.7"

before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.7.4.zip -nv
  - unzip -q google_appengine_1.7.4.zip

# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
