language: python
python:
  - "2.7"

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.15.zip -nv
  - unzip -q google_appengine_1.9.15.zip
  - ln -s google_appengine/google/appengine/tools/old_dev_appserver.py
  - export PATH = google_appengine : $PATH

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests -v --with-gae --without-sandbox
