application: trackdidia
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: trackdidia/static
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /crons
  script: trackdidia.main.app
  login: admin

- url: .*
  script: trackdidia.main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
- name: django
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- trackdidia/static/js/app/src
- trackdidia/static/css/src
- node_modules